# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftMVVMSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftMVVMSampleApp

  target 'RxSwiftMVVMSampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftMVVMSampleAppUITests' do
    # Pods for testing
  end
pod 'RxSwift'
pod 'RxCocoa'

end
